version: "3.8"

services: 
  udm:
    build:
      context: ./udm
      dockerfile: Dockerfile
    container_name: udm
    restart: unless-stopped
    ports:
      - "8082:8082"
    cpuset: "4"
    #mem_limit: "256m"
    networks:
      core-net:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_DSN=root:my-secret-pw@tcp(172.20.0.3:3306)/udm?charset=utf8mb4&parseTime=True&loc=Local

  smf:
    build:
      context: ./smf
      dockerfile: Dockerfile
    container_name: smf
    restart: no #unless-stopped
    ports:
      - "8081:8081"
    cpuset: "1"
    mem_limit: "256m"
    networks: 
      core-net:
        ipv4_address: 172.20.0.11
    environment:
      - AMF_BASE_URL=https://172.20.0.12:8080
      - UDM_BASE_URL=https://172.20.0.10:8082
      - UPF_BASE_URL=upf:8805   
  upf:
    build:
      context: ./upf
      dockerfile: Dockerfile
    container_name: upf
    restart: unless-stopped
    ports:
      - "8805:8805"
    cpuset: "2"
    mem_limit: "256m"
    networks: 
      - core-net

  amf:
    build:
      context: ./amf
      dockerfile: Dockerfile
    container_name: amf
    profiles:
      - 'manual'
    restart: no #unless-stopped
    ports:
      - "8080:8080"
    cpuset: "3"
    #mem_limit: "256m"
    depends_on:
      - smf
    networks:
      core-net:
        ipv4_address: 172.20.0.12
    environment:
      - SMF_BASE_URL=https://172.20.0.11:8081  
networks:
  core-net:
    driver: bridge

