version: "3.8"

services: 
  udm:
    build:
      context: ./udm
      dockerfile: Dockerfile
    container_name: udm
    restart: unless-stopped
    ports:
      - "8082:8082"
    cpus: "1.0"
    mem_limit: "256m"
    networks:
      - core-net
    environment:
      - MYSQL_DSN=root:my-secret-pw@tcp(udm-mysql:3306)/udm?charset=utf8mb4&parseTime=True&loc=Local

  smf:
    build:
      context: ./smf
      dockerfile: Dockerfile
    container_name: smf
    restart: no #unless-stopped
    ports:
      - "8081:8081"
    cpus: "1.0"
    mem_limit: "256m"
    networks: 
      - core-net
    environment:
      - AMF_BASE_URL=http://amf:8080
      - UDM_BASE_URL=http://udm:8082
      - UPF_BASE_URL=upf:8805   
  upf:
    build:
      context: ./upf
      dockerfile: Dockerfile
    container_name: upf
    restart: unless-stopped
    ports:
      - "8805:8805"
    cpus: "1.0"
    mem_limit: "256m"
    networks: 
      - core-net

  amf:
    build:
      context: ./amf
      dockerfile: Dockerfile
    container_name: amf
    restart: no #unless-stopped
    ports:
      - "8080:8080"
    cpus: "1.0"
    mem_limit: "256m"
    networks:
      - core-net
    environment:
      - SMF_BASE_URL=http://smf:8081  
networks:
  core-net:
    driver: bridge

