apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: 5gcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
      - name: upf
        image: thanhlongnguyen1012/5gcore-upf:latest
        ports:
        - containerPort: 8805
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: 5gcore
spec:
  selector:
    app: upf
  ports:
  - protocol: TCP
    port: 8805
    targetPort: 8805
  type: ClusterIP
